# Setup and Data Loading

In [18]:
import numpy as np
import pandas as pd
import os

covariance_csv_path = r'F:\Learning_journal_at_CUHK\FTEC5610_Computational_Finance\Assignment\Assignment 1\Part1_calculation\Annualized covariance between ETF.csv'

std_dev_csv_path = r'F:\Learning_journal_at_CUHK\FTEC5610_Computational_Finance\Assignment\Assignment 1\Part1_calculation\Annualized standard deviation of daily return of ETF.csv'

# all the resulting CSV files will be saved here
output_dir = r'F:\Learning_journal_at_CUHK\FTEC5610_Computational_Finance\Assignment\Assignment 1\Part3_calculation\data'

os.makedirs(output_dir, exist_ok=True)

# load
covariance_df = pd.read_csv(covariance_csv_path)
std_dev_df = pd.read_csv(std_dev_csv_path)

In [19]:
covariance_df

2823     3199     2840     3175     3046
0  0.08137 -0.00027  0.00546  0.01881  0.03654
1 -0.00027  0.00279  0.00077  0.00078  0.00002
2  0.00546  0.00077  0.03070  0.01293 -0.00571
3  0.01881  0.00078  0.01293  0.11040  0.05456
4  0.03654  0.00002 -0.00571  0.05456  0.63990

In [20]:
std_dev_df

2823     3199     2840     3175     3046
0  0.28526  0.05283  0.17521  0.33227  0.79994

## Transform for Matric Operation

In [21]:
# convert the covariance df to a NumPy array for matrix operations
covariance_matrix_full = covariance_df.values
# get the asset names from the DataFrame's columns.
asset_names_full = covariance_df.columns.tolist()

# Convert the standard deviation DataFrame to a 1D NumPy array.
std_dev_full = std_dev_df.values[0]

# Four-Asset Portfolio Analysis

In [22]:
num_assets_4 = 4
# slice the full covariance matrix to get a 4x4 matrix.
covariance_matrix_4 = covariance_matrix_full[:num_assets_4, :num_assets_4]
asset_names_4 = asset_names_full[:num_assets_4]
std_dev_4 = std_dev_full[:num_assets_4]

In [23]:
# (a) Equal Weight (EW) Portfolio

# for an EW portfolio with N assets, each weight is 1/N.
ew_weights_4 = np.array([1/num_assets_4] * num_assets_4)
# calculate portfolio variance using the matrix formula: w^T * Σ * w
ew_variance_4 = ew_weights_4.T @ covariance_matrix_4 @ ew_weights_4
# portfolio standard deviation is the square root of the variance.
ew_std_dev_4 = np.sqrt(ew_variance_4)

In [24]:
ew_weights_4

array([0.25, 0.25, 0.25, 0.25])

In [25]:
ew_variance_4

0.018888749999999996

In [26]:
ew_std_dev_4

0.13743634890377435

In [27]:
# save to csv
ew_results_4_df = pd.DataFrame({
    'Asset': asset_names_4 + ['Portfolio'],
    'Value_Type': ['Weight'] * num_assets_4 + ['Std_Dev'],
    'Value': np.append(ew_weights_4, ew_std_dev_4)
})
ew_output_path = os.path.join(output_dir, 'four_asset_EW_results.csv')
ew_results_4_df.to_csv(ew_output_path, index=False, float_format='%.5f')

In [28]:
# (b) Minimum Variance (MV) Portfolio 
# formula for MV weights is: w = (Σ^-1 * 1) / (1^T * Σ^-1 * 1)
# calculate the inverse of the 4x4 covariance matrix.
inv_covariance_matrix_4 = np.linalg.inv(covariance_matrix_4)
# Create a 4x1 vector of ones.
ones_vector_4 = np.ones(num_assets_4)

# calculate the numerator of the formula: Σ^-1 * 1
numerator_4 = inv_covariance_matrix_4 @ ones_vector_4
# calculate the denominator of the formula: 1^T * Σ^-1 * 1
denominator_4 = np.sum(numerator_4)

# calculate the final MV weights.
mv_weights_4 = numerator_4 / denominator_4
# calculate the portfolio variance with the new MV weights.
mv_variance_4 = mv_weights_4.T @ covariance_matrix_4 @ mv_weights_4
# calculate the portfolio standard deviation.
mv_std_dev_4 = np.sqrt(mv_variance_4)

In [29]:
mv_weights_4

array([0.029843  , 0.91106965, 0.05351231, 0.00557504])

In [30]:
mv_variance_4

0.002579379719480671

In [31]:
mv_std_dev_4

0.05078759414936556

In [32]:
# save to csv
mv_results_4_df = pd.DataFrame({
    'Asset': asset_names_4 + ['Portfolio'],
    'Value_Type': ['Weight'] * num_assets_4 + ['Std_Dev'],
    'Value': np.append(mv_weights_4, mv_std_dev_4)
})
# Add intermediate calculation results
mv_intermediate_df = pd.DataFrame({
    'Asset': [f'Numerator_{i+1}' for i in range(num_assets_4)] + ['Denominator'],
    'Value_Type': ['Intermediate_Calc'] * (num_assets_4 + 1),
    'Value': np.append(numerator_4, denominator_4)
})
mv_full_results_4_df = pd.concat([mv_results_4_df, mv_intermediate_df], ignore_index=True)
mv_output_path = os.path.join(output_dir, 'four_asset_MV_results.csv')
mv_full_results_4_df.to_csv(mv_output_path, index=False, float_format='%.5f')

# Five-Asset Portfolio Analysis

In [33]:
# for this section, we use the full data loaded earlier.
num_assets_5 = 5

# (a) EW
ew_weights_5 = np.array([1/num_assets_5] * num_assets_5)
ew_variance_5 = ew_weights_5.T @ covariance_matrix_full @ ew_weights_5
ew_std_dev_5 = np.sqrt(ew_variance_5)

ew_results_5_df = pd.DataFrame({
    'Asset': asset_names_full + ['Portfolio'],
    'Value_Type': ['Weight'] * num_assets_5 + ['Std_Dev'],
    'Value': np.append(ew_weights_5, ew_std_dev_5)
})
ew_output_path_5 = os.path.join(output_dir, 'five_asset_EW_results.csv')
ew_results_5_df.to_csv(ew_output_path_5, index=False, float_format='%.5f')


In [34]:
ew_weights_5

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [35]:
ew_variance_5

0.04451760000000001

In [36]:
ew_std_dev_5

0.2109919429741335

In [37]:
# (b) MV
inv_cov_matrix_5 = np.linalg.inv(covariance_matrix_full)
ones_vector_5 = np.ones(num_assets_5)
numerator_5 = inv_cov_matrix_5 @ ones_vector_5
denominator_5 = np.sum(numerator_5)
mv_weights_5 = numerator_5 / denominator_5
mv_variance_5 = mv_weights_5.T @ covariance_matrix_full @ mv_weights_5
mv_std_dev_5 = np.sqrt(mv_variance_5)

mv_results_5_df = pd.DataFrame({
    'Asset': asset_names_full + ['Portfolio'],
    'Value_Type': ['Weight'] * num_assets_5 + ['Std_Dev'],
    'Value': np.append(mv_weights_5, mv_std_dev_5)
})
mv_intermediate_df_5 = pd.DataFrame({
    'Asset': [f'Numerator_{i+1}' for i in range(num_assets_5)] + ['Denominator'],
    'Value_Type': ['Intermediate_Calc'] * (num_assets_5 + 1),
    'Value': np.append(numerator_5, denominator_5)
})
mv_full_results_5_df = pd.concat([mv_results_5_df, mv_intermediate_df_5], ignore_index=True)
mv_output_path_5 = os.path.join(output_dir, 'five_asset_MV_results.csv')
mv_full_results_5_df.to_csv(mv_output_path_5, index=False, float_format='%.5f')


In [38]:
mv_weights_5

array([0.02889623, 0.90970855, 0.0545602 , 0.00437437, 0.00246065])

In [39]:
mv_variance_5

0.0025757574588125345

In [40]:
mv_std_dev_5

0.050751920740130956